### ISSUE TITLE
Update on f-droid

### ISSUE THREAD

**Issue by BedHead911** [romannurik/muzei#204]
Can you update muzei app on f-droid to the latest version? The last update was from 2014. This is my favorite wallpaper app and I really miss it after purging google from my android phone.

**Comment by ianhanniballake** [comment]
Per #127 Muzei relies on Google Play services and that means it does not fall under F-Droid's [inclusion policy](https://f-droid.org/wiki/page/Inclusion_Policy)

**Comment by SpotComms** [comment]
Here is a patch that applies cleanly after 7815d43fdd6e59e04abe940300eec1ead9505667. 
I don't plan on maintaining it, but the result is better than the two year old build available on F-Droid. Putting it here for anyone who wants to build themselves, because the Muzei team seems to not care at all and the F-Droid team is too busy to maintain/verify patches like this.
[Remove_Wearable.patch.txt](https://github.com/romannurik/muzei/files/275244/Remove_Wearable.patch.txt)

**Comment by ildar** [comment]
Sorry for tickling, no change in the the point of view here? 2+ years may have changed something...

**Comment by ianhanniballake** [comment]
There's been no change in F-Droid's inclusion policy, so no change in what Muzei can do.

**Comment by ildar** [comment]
Sorry to disturb

**Comment by PanderMusubi** [comment]
@ildar @BedHead911 Meanwhile, F-Droid does build newer versions without Google Play services, see https://f-droid.org/wiki/page/net.nurik.roman.muzei#Maintainer_Notes
