### ISSUE TITLE
Muzei is killing my battery

### ISSUE THREAD

**Issue by robotvert** [romannurik/muzei#493]
So I have made a custom plugin to use Dropbox as an art source inspired a lot by the [National Geographic](https://github.com/msal/muzei-nationalgeographic) plugin.

In `onTryUpdate` the very first thing I do is checking for Wifi [just like in the aforementioned plugin](https://github.com/msal/muzei-nationalgeographic/blob/3aeac1641506074ffb9edd82b3c2b02f4e010e24/muzei-nationalgeographic/src/java/de/msal/muzei/nationalgeographic/NationalGeographicArtSource.java#L229-L235) and likewise throw a [RetryException](http://api.muzei.co/reference/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.RetryException.html) if not on Wifi.
The API docs say it should use an exponential backoff on fail, which as I understand it means "retry less and less frequently if you keep failing" but this is not really what I see happening:

```
10-25 21:00:07.608 12443 14044 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:01:09.251 12443 14077 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:01:46.315 12443 14108 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:02:09.322 12443 14132 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:03:09.315 12443 14148 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:03:19.325 12443 14222 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:03:36.513 12443 14238 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:05:29.251 12443 14253 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:07:30.354 12443 14295 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:09:30.442 12443 14341 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:11:30.495 12443 14401 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:14:31.366 12443 14448 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:14:41.554 12443 14481 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:16:30.607 12443 14564 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:18:31.359 12443 14637 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:19:04.985 12443 14686 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:20:47.320 12443 14884 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:22:30.620 12443 14988 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:25:29.389 12443 15028 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:26:20.545 12443 15075 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:28:30.628 12443 15091 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:30:35.341 12443 15145 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:31:29.380 12443 15170 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:34:31.312 12443 15214 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:35:41.315 12443 15258 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:36:17.321 12443 15296 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:36:27.900 12443 15303 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:37:36.254 12443 15321 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:39:29.329 12443 15353 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:40:35.326 12443 15387 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:40:45.336 12443 15399 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:42:42.172 12443 15419 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:43:36.334 12443 15442 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:45:52.356 12443 15483 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:46:45.357 12443 15529 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:47:47.311 12443 15549 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:49:31.494 12443 15567 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:49:41.515 12443 15572 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:50:58.240 12443 15614 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:51:19.894 12443 15639 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:52:53.321 12443 15658 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:56:04.339 12443 15708 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:56:14.395 12443 15743 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:56:27.678 12443 16188 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
10-25 21:58:53.336 12443 16558 W MuzeiArtSource: Error fetching, scheduling retry, id=DropboxFolderArtSource
```

That's 45 attempts within one hour which basically wakes up my phone all the time.

Actually how I noticed it was even it's in my pocket doing nothing the phone was getting warm.
Checking out the battery usage yielded:

![screenshot_20171025-204822](https://user-images.githubusercontent.com/514215/32002663-f5f506fc-b9d7-11e7-8a3a-b4b4f896a813.png)
![screenshot_20171025-204933](https://user-images.githubusercontent.com/514215/32002664-f61d6f48-b9d7-11e7-9ba9-1e27700b237a.png)
![screenshot_20171025-204925](https://user-images.githubusercontent.com/514215/32002666-f6975c22-b9d7-11e7-995b-b208fb2ab868.png)

FWIW in my plugin I set the update frequency to 8 hours and I'm using a Nexus 5 with stock Android 6.0.1.

Any ideas as to how to fix this? What's the best way to handle such "do only on Wifi" cases?

**Comment by ianhanniballake** [comment]
In the [new API](https://medium.com/@ianhlake/the-muzei-plugin-api-and-androids-evolution-9b9979265cfb), only loading under Wifi (and customizing the update frequency) is planned to be a feature on the Muzei side and not something your plugin would need to handle.

Right now, the exponential backoff only applies in cases where [onUpdate() is called when the network isn't connected](https://github.com/romannurik/muzei/blob/v2.3/api/src/main/java/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.java#L94). I suspect to handle your case, [this section](https://github.com/romannurik/muzei/blob/v2.3/api/src/main/java/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.java#L99) should be done after `onTryUpdate()` rather than before.

You'll still get a callback whenever the network changes since the current API is that it also [calls `setWantsNetworkAvailable(true)`](https://github.com/romannurik/muzei/blob/v2.3/api/src/main/java/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.java#L115) when handling a `RetryException`. This will definitely trigger your `onTryUpdate()` possibly many times before you get a Wifi connection, but it will eventually lead to you being triggered right after a wifi network becomes available, as you might want.

Creating your own subclass of `MuzeiArtSource` that copies `RemoteMuzeiArtSource` with the above reordering is probably the best short term plan as there are no plans to publish an update to the current API (or just roll your own `RetryException` and call `scheduleUpdate()`, etc. yourself).

The first alpha release of the new API, which hopefully will be in the next ~2 months, should make this case and many others much easier. Joining the [Muzei G+ community](https://plus.google.com/communities/114043146173681149763) is the best way to keep on top of updates.

**Comment by robotvert** [comment]
Thanks for the very thorough answer!

As you suggest, I guess I'll just copy/paste that RemoteMuzeiArtSource class and add the "am I on Wifi?" check right after the "am I connected?" one so that the exponential backoff works in both cases.
I don't direly need that the art source gets updated soon-ish after getting Wifi but dealing with re-scheduling and such seems to be more work for a fix with a limited timespan.

Looking forward to the next release!
