### ISSUE TITLE
Requesting artwork load from Provider

### ISSUE THREAD

**Issue by timusus** [romannurik/muzei#598]
I'm looking at updating [MuzeiMusicExtension](https://github.com/timusus/MuzeiMusicExtension) to use the 3.0 API.

This extension detects changes to the current song playing on the user's device, and displays the appropriate artwork.

With 3.0, if I understand correctly, choosing when to load artwork is entirely the responsibility of Muzei itself, and we can only respond to requests to change artwork initiated by the 'auto advance' feature. Is that correct?

If that is the case, then i'd like to request a method to workaround auto-advance for apps where 'advancing' doesn't make sense.

**Comment by ianhanniballake** [comment]
If you have just a single artwork (as I would expect if you're tying it to what is currently playing), then you would not have a 'Next Artwork' button and Auto Advance would not apply - you'd ignore callbacks to `onLoadRequested()` as you would fully own the loading of artwork.

Instead, you would call `setArtwork()` at any time to update your current artwork. Since you can call `ProviderContract.getProviderClient()` from anywhere in your app, you don't need to do the dance of starting your `MuzeiArtSource` with a custom Intent just to call `publishArtwork`.

**Comment by timusus** [comment]
OK, thanks for clarifying.
