### ISSUE TITLE
Question regarding migrating to the new Muzei API

### ISSUE THREAD

**Issue by adrianaisemberg** [romannurik/muzei#599]
My app ("Tapet") was using the old API (`MuzeiArtSource`) and I am now migrating to use the new `MuzeiArtProvider`.
I have a few questions:
1. My app generates all images in memory. Previously I was saving the image in a temporary file and using `new Artwork.Builder().imageUri(...)...` to build the artwork object.
I don't see `imageUri` anymore in the new API. Which method replaced it?
2. I was also using `viewIntent(intent)` to provide an intent for opening the app, if the user wants to.
I don't see it anymore. What replaced it?
3. After calling `publishArtwork` to apply the wallpaper, I was calling `scheduleUpdate` to schedule the next update based on Tapet's interval. This one is also missing in the new API. Is there a replacement?

Thank you!

**Comment by ianhanniballake** [comment]
I'd really suggest reading the [Muzei 3.0 and the new API blog post](https://medium.com/muzei/muzei-3-0-and-the-new-api-4fd3d6133db6), which covers the API in detail.

1. `imageUri` is replaced by `persistentUri`, but you don't need to use that at all - it is not required for the 3.0 API. Just override `openFile` in your `MuzeiArtProvider` to provide an `InputStream` (such as a `ByteArrayInputStream`) to your image.

2. Override `openArtworkInfo` in your `MuzeiArtProvider`.

3. Muzei 3.0 centralizes the update schedule, as per the [Muzei 3.0 and the new API blog post](https://medium.com/muzei/muzei-3-0-and-the-new-api-4fd3d6133db6). You should remove any interval scheduling you have on your end.

The fundamental difference with the new API is that you add **all** of your Artwork and Muzei rotates between them, instead of you just providing a single artwork at a time to Muzei.

Note that the best place to contact us is via [support@muzei.co](mailto:support@muzei.co), not via the issue tracker.
