### ISSUE TITLE
>> button disappeared.

### ISSUE THREAD

**Issue by fusk-l** [romannurik/muzei#618]
Using 3.2.0 alpha 4. Also using vitrina and tried bing as well. Also tried uninstalling everything and reinstalling. So what happens is you open muzei and the default starry night open, all good >> is there, but if i press it, it loads the next image and then the button disappears. On 3'th party apps like bing and vitrina the button never appears and is always gone.
The shortcut in the pull down bar is also greyed out.
I have not experienced this before, so no idea what's going on.
Device is 1+7 on android 9.

**Comment by ianhanniballake** [comment]
If you are using the 'Featured Art' source (which it sounds like you are, given that's the source that the Starry Night background comes from), it only shows one image a day and everyone has the same image. Since there's only one image from that source, there's no Next button. The Featured Art loads images on its own schedule, once a day and, if you have Auto Advance enabled, Muzei will automatically switch to that new image (if you had it disabled, you'd see the Next button and have to manually hit it to twice to the new artwork). That's all working as intended.

You can check if your third party source only has one image by opening Muzei from the app icon, going to Sources, then hitting the 'Browse' button underneath the source you have selected. If you only see one image, then the Source has only provided one image to Muzei to display. If you think that's in error, you should contact the developer of the third party source - Muzei only displays what they've sent to us.

If you're seeing multiple images in Browse and don't see the >> next button, then that would be a bug on Muzei's side. We'd need you to [take a bug report](https://tamingthedroid.com/take-bug-report) immediately after seeing this happen and send it to [support@muzei.co](mailto:support@muzei.co).

**Comment by fusk-l** [comment]
I see, 3'th party sources only has 1 picture in browse. So if i understand it correctly it's the source that's broken for not allowing to skip images. Auto advance is on 15 min as a test, and vitrina for one is not loading new images. What is a bit weird is that vitrina was last updated 16/1, so it hasn't changed.

**Comment by fusk-l** [comment]
Just wondering, can unsupported sources interfere? 
I have some icon packs installed and muzei recognized them as sources and states they're unsupported.

**Comment by ianhanniballake** [comment]
Looking through the reviews of Vitrina, it looks like [you aren't the only one](https://play.google.com/store/apps/details?id=stoyck.vitrina&reviewId=gp%3AAOqpTOFf_GsnmwXY2-b9UWUVU1Z5AidABwgAXi-qlq13xmcnLdV1HxcP7S8p3JFvic321ZRlaxAsG0XSfUH_jg). I don't know why they'd get stuck with just one image though - I would have thought you wouldn't delete any existing images unless you get a non-empty set of new images back. Certainly something to contact that developer about to see if they can improve their logic.

Each Source is completely independent from one another (they're separate apps after all), so what images a Source provides to Muzei would not be affected by other Sources.
