### ISSUE TITLE
Allow custom command start activity

### ISSUE THREAD

**Issue by james58899** [romannurik/muzei#644]
Android 10 restriction start activity on background service, so app can't start activity in `onCommand` method.

Maybe can change `onCommand` return `PendingIntent` like `getArtworkInfo` to allow start activity.

**Comment by ianhanniballake** [comment]
We're actually looking at solving this slightly differently, where `getCommands()` would return a list of [`RemoteActionCompat`](https://developer.android.com/reference/androidx/core/app/RemoteActionCompat) objects rather than `UserCommand`, allowing you to tie an action directly to any `PendingIntent` you want (i.e., to start an activity) as an alternative to using the default `onCommand` callback (which will still be available).

(As a side benefit, it'll let you attach a custom icon to your action)
