### ISSUE TITLE
Display background proportionally

### ISSUE THREAD

**Issue by returntrip** [romannurik/muzei#657]
I use Lawnchair Launcher (but this issue seems to happen also with the stock OnePlus Launcher). I do not use Google Now or the likes (so I have no additional workspace when swiping left, relative to the default workspace)

The background image is not shown in its entirety through the three panes/pages of my desktop setup.

I can only see the central part and the edges are not shown (say about 1/6 of the whole image on each side).

Would it be possible to show the background image in proportion to the number of panes.

Examples:
Wallpaper: [---------]
3x - panes: [x][x][x]
2x - panes: [xx][xx]

Hope it makes sense!

**Comment by ianhanniballake** [comment]
Here's how Muzei works:
1. The launcher provides us with a height and a width. The height is generally always the height of your device. The width is where things vary quite a bit by launcher - some launcher provide more width for the number of pages you've set up, others don't, and others have a wallpaper scrolling option to switch between the two. **Muzei has no idea how many pages you have** - it only gets the total dimensions.
2. Since Muzei never changes the aspect ratio of the image, it fits the image to the dimensions provided by the launcher. If the aspect ratios don't fit exactly (say, the image is really wide), then Muzei will center crop the image into the size available so the wallpaper goes edge to edge without any black bars.

It sounds like your image's aspect ratio just doesn't match the aspect ratio your launcher is providing, hence Muzei is cropping the image to avoid black bars. That's working as intended, although there's an open feature request in #196 for being able to zoom out enough to see the entire wallpaper when you have Muzei open.

**Comment by returntrip** [comment]
Thanks for the clarification. It makes sense now.

Assuming that the launcher would provide the width value, would it be technically possible for Muzei to apply aspect ratio coversion to match the launcher's width? Of course, this would be just an option, as it might not work for all launchers.

**Comment by ianhanniballake** [comment]
That's already what it does: if you had a really tall image, for instance, Muzei would center crop the image so that the width matches the width the launcher provides and the top and bottom would be cropped off: again, showing as much of the image as possible while keeping no black bars and maintaining the aspect ratio.
