### ISSUE TITLE
Cut headers in 'Sources' screen

### ISSUE THREAD

**Issue by strievi** [romannurik/muzei#674]
Long titles won't fit, would be nice to have them split into multiple lines.

**Comment by ianhanniballake** [comment]
Can you attach a picture?

**Comment by strievi** [comment]
[Here](https://user-images.githubusercontent.com/43119811/87247930-fe3f1500-c456-11ea-9d91-f5fb9dcea057.png), first one is supposed to read 'Muzei - Bing Image of the Day'. I guess second is 'Obtenir d'autres sources'.

**Comment by strievi** [comment]
> [Here](https://user-images.githubusercontent.com/43119811/87247930-fe3f1500-c456-11ea-9d91-f5fb9dcea057.png), first one is supposed to read 'Muzei - Bing Image of the Day'. I guess second one is 'Obtenir d'autres sources'.

[Tablet layout](https://user-images.githubusercontent.com/43119811/87256398-6c54fd80-c492-11ea-90a4-2604d37e0685.png), for comparison.

**Comment by ianhanniballake** [comment]
Thanks, we've fixed the layout to support multiple line titles - it'll be available in the next release of Muzei.

FWIW, I'd strongly suggest reaching out to the 'Muzei - Bing Image of the Day' developer - they can add an `android:label` to their `<provider>` to provide a custom label specifically for the Sources screen: there's no reason to put a prefix of "Muzei - " in front of their title since you're already in Muzei when you're seeing that title.

**Comment by strievi** [comment]
> FWIW, I'd strongly suggest reaching out to the 'Muzei - Bing Image of the Day' developer - they can add an `android:label` to their `<provider>` to provide a custom label specifically for the Sources screen: there's no reason to put a prefix of "Muzei - " in front of their title since you're already in Muzei when you're seeing that title.

Thanks for pointing that out, keep up the good work!
