### ISSUE TITLE
Image cropping/centering

### ISSUE THREAD

**Issue by rain1273** [romannurik/muzei#695]
I would love to see a feature that allows to disable wallpaper scrolling i.e. the ability to choose where to center and/or crop the image.

**Comment by ianhanniballake** [comment]
We've covered this request previously in #13, #62, #64, and #594 and nothing has changed since those requests when it comes to what the live wallpaper API allows Muzei to do in a consistent way across all launchers (and it is launchers that control wallpaper scrolling, what is visible, etc. - that's why many launchers, such as Nova Launcher and Action Launcher, already have an option to disable wallpaper scrolling).
