### ISSUE TITLE
Export PNG to SVG to use in  AnimatedMuzeiLogoView

### ISSUE THREAD

**Issue by alirezazarghi** [romannurik/muzei#702]
hi , plz learn me to Export , thx all

**Comment by ianhanniballake** [comment]
This is, in general, never going to work. An SVG (or SVG path such that `AnimatedMuzeiLogoView`) is a set of instructions in how to draw a certain shape. While it is easy to follow an SVG's instructions to draw a PNG (a process called [rasterization](https://en.wikipedia.org/wiki/Rasterisation)), you can't generate the instructions from a PNG since you are inherently losing information when you do that.

It would be like being given a completed Lego set and asking for someone to generate the instructions on how to build that set - you may be able to guess or figure something out, but it certainly won't match the included instructions which is really what you're asking for.

There may certainly be utilities to approximate this conversion (something you could Google search for), but they won't ever be perfect. In general, a designer builds an icon first in SVG or another vector graphic format and *then* you generate the PNG from that, not the other way around.

Best of luck!
